# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569755122c1e818ab1da40d45e0559de6f3fa69576651c165a753bd835f70328986a8509e2ee493f5435233215cc392e98c407ff088572ebdabac5c3c1ebee53

test:
  secret_key_base: 882ed20caac173e45c57fd970d7b8490734e631a486ade7d9f693b168723f07138edf9cacb5a99806e707b06b48d3d7656851df5a96bfea517c8c86470d7aeb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
